baseurl = "http://yourdomain.com"
languageCode = "en-us"
title = "Best Alternative To Payday"
canonifyUrls = "true"

[params]
    description = "You seem to take the word loan and change it to oppurtunity."
    custom_css = ["css/local.css","css/custom.css"]
    subDescription = "-MITCHELL P, LendUp Customer"
    note = "Why Lend Up"
  
[[params.social]]
    title = "email"
    icon = "envelope-o"
    url = "mailto:bushbama@whitehouse.gov"
[[params.social]]
    title = "twitter"
    icon = "twitter"
    url = "https://twitter.com/SBootstrap"
[[params.social]]
    title = "github"
    icon = "github"
    url = "https://github.com/IronSummitMedia/startbootstrap"
[[params.social]]
    title = "linkedin"
    icon = "linkedin"
    url = "http://linkedin.com/in/yourusername"
